<ul>
<li>About Us</li>
<li>Contact informtion</li>
<li>About the Company</li>
<li>Ours Location</li>
<li>Dirction</li>
<h2>About Us</h2>
<li>Contact infomation</li>
<li>About HP</li>
<li>Our Location</li>
<li>Dirctions</li>
<div>From the North</div>
<div>From the South</div>
</ul>
The vcl_recv subroutine handles the incoming request from the client. This is where you set basic config options and do any request setup and tweaking before varnish looks up the item or passes.
<footer>Home | About HP</footer>
